services:
  - type: web
    name: managemytask
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic
      python manage.py migrate
    startCommand: gunicorn TaskManager.wsgi
    staticPublishPath: staticfiles