# Generated by Django 5.0.6 on 2024-06-23 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('IP', 'In Progress'), ('CO', 'Completed'), ('OV', 'Overdue')], default='IP', max_length=2)),
                ('priority', models.CharField(choices=[('LO', 'Low'), ('ME', 'Medium'), ('HI', 'High')], max_length=2)),
                ('due_date', models.DateTimeField()),
                ('category', models.CharField(max_length=255)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
