# Generated by Django 5.0.6 on 2024-06-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_task'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('title', 'assigned_to')},
        ),
    ]
