name: Django Migrations

on:
  push:
    branches:
      - main  # Or your default branch name

jobs:
  migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate
        env:
          DJANGO_SETTINGS_MODULE: TaskManager.settings  # Adjust to your project
